/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package workspace

import workspace.day1.Day1Solver
import workspace.day2.Day2Solver
import workspace.day3.Day3Solver
import workspace.day4.Day4Solver
import workspace.day5.Day5Solver
import workspace.day6.Day6Solver
import workspace.day7.Day7Solver
import workspace.day8.Day8Solver
import workspace.day9.Day9Solver
import workspace.day10.Day10Solver

fun main() {
    // println(Day1Solver().part1())
    // println(Day1Solver().part2())
    // println(Day2Solver().part1())
    // println(Day2Solver().part2())
    // println(Day3Solver().part1())
    // println(Day3Solver().part2())
    // println(Day4Solver().part1())
    // println(Day4Solver().part2())
    // println(Day5Solver().part1())
    // println(Day5Solver().part2()) // takes 8.5 minutes to run
    // println(Day6Solver().part1())
    // println(Day6Solver().part2())
    // println(Day7Solver().part1())
    // println(Day7Solver().part2())
    // println(Day8Solver().part1())
    // println(Day8Solver().part2())
    // println(Day9Solver().part1())
    // println(Day9Solver().part2())
    // println(Day10Solver().part1())
    // println(Day10Solver().part2())
}
