/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package workspace

import workspace.day1.Day1Solver
import workspace.day2.Day2Solver
import workspace.day3.Day3Solver
import workspace.day4.Day4Solver

fun main() {
    // println(Day1Solver().part1())
    // println(Day1Solver().part2())
    // println(Day2Solver().part1())
    // println(Day2Solver().part2())
    // println(Day3Solver().part1())
    // println(Day3Solver().part2())
    // println(Day4Solver().part1())
    // println(Day4Solver().part2())
}
