/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package workspace

import workspace.day1.Day1Solver
import workspace.day2.Day2Solver

fun main() {
    // println(Day1Solver().part1())
    // println(Day1Solver().part2())
    // println(Day2Solver().part1())
    // println(Day2Solver().part2())
}
